import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Select;
import java.util.concurrent.TimeUnit;

public class a101caseOne {
    public static void main(String[] args) throws InterruptedException  {
        System.setProperty("webdriver.chrome.driver","C:\\Selenium\\chromedriver_win32\\chromedriver.exe");
        WebDriver driver = new ChromeDriver();
        driver.get("https://www.a101.com.tr/");
        System.out.println("www.a101.com.tr sayfası açıldı.");
        TimeUnit.SECONDS.sleep(2);
        driver.findElement(By.xpath("//*[@id=\"CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll\"]")).click();
        System.out.println("Çerezler kabul edildi.");
        TimeUnit.SECONDS.sleep(1);
        ((JavascriptExecutor) driver).executeScript("window.location=document.getElementsByClassName('js-navigation-item')[3].getElementsByTagName('*')[0].href;");
        System.out.println("Giyim ve Aksesuar kategorisi açıldı.");
        TimeUnit.SECONDS.sleep(1);
        driver.findElement(By.xpath("/html/body/section/section[4]/div[3]/div[3]/div/div[1]/div[1]/div[1]/ul/li[6]/a")).click();
        System.out.println("Kadın iç giyim kategorisi açıldı.");
        TimeUnit.SECONDS.sleep(1);
        driver.findElement(By.xpath("/html/body/section/section[4]/div[3]/div[2]/div/div[1]/div[1]/div[1]/ul/li[4]/a")).click();
        System.out.println("Diz altı çorap kategorisi seçildi. ");
        TimeUnit.SECONDS.sleep(1);
        driver.findElement(By.xpath("/html/body/section/section[4]/div[3]/div[2]/div/div[1]/div[1]/div[2]/ul[4]/li[2]/label")).click();
        System.out.println("Siyah renk filtresi seçildi. ");
        TimeUnit.SECONDS.sleep(1);
        driver.findElement(By.xpath("/html/body/section/section[4]/div[3]/div[2]/div/div[2]/div[2]/div/ul/li[1]/article/div/div[2]/div[2]/a/strong/span")).click();
        System.out.println("Ürün detayına gidildi.");
        TimeUnit.SECONDS.sleep(1);
        driver.findElement(By.xpath("/html/body/section/section[3]/div[2]/div[1]/div/div[3]/div[2]/div[1]/button")).click();
        System.out.println("Ürün sepete eklendi.");
        TimeUnit.SECONDS.sleep(1);
        driver.findElement(By.linkText(driver.findElement(By.xpath("//*[@id=\"js-modal-basket\"]/div[3]/a[3]")).getText())).click();
        System.out.println("Sepete gidildi.");
        TimeUnit.SECONDS.sleep(1);
        driver.findElement(By.linkText(driver.findElement(By.xpath("/html/body/section/div[1]/div[2]/div/div[2]/div/a")).getText())).click();
        System.out.println("Sepet onaylandı.");
        TimeUnit.SECONDS.sleep(1);
        driver.findElement(By.linkText(driver.findElement(By.xpath("/html/body/section/div[1]/div/div[1]/div[1]/div[2]/a")).getText())).click();
        System.out.println("Üye olmadan devam edildi.");
        TimeUnit.SECONDS.sleep(1);
        driver.findElement(By.xpath("/html/body/section/div[1]/div/div[2]/div/div/form/div[1]/input")).sendKeys("r.rabiadmr.r@gmail.com");
        System.out.println("Mail hesabı yazıldı.");
        TimeUnit.SECONDS.sleep(1);
        driver.findElement(By.xpath("/html/body/section/div[1]/div/div[2]/div/div/form/button")).click();
        System.out.println("Devam et butonuna tıklandı.");
        TimeUnit.SECONDS.sleep(1);
        driver.findElement(By.xpath("/html/body/section/section/div/div[2]/div/div[1]/div/div[1]/div[2]/ul[2]/li/a")).click();
        System.out.println("Adres popup'ı açıldı.");
        driver.findElement(By.xpath("//*[@id=\"js-orders-modal-container\"]/div/div[2]/form/div[2]/div/div/label/input")).sendKeys("Ev Adresim");
        TimeUnit.SECONDS.sleep(1);
        driver.findElement(By.xpath("//*[@id=\"js-orders-modal-container\"]/div/div[2]/form/div[3]/div[1]/div/label/input")).sendKeys("Rabia");
        TimeUnit.SECONDS.sleep(1);
        driver.findElement(By.xpath("//*[@id=\"js-orders-modal-container\"]/div/div[2]/form/div[3]/div[2]/div/label/input")).sendKeys("Demir");
        TimeUnit.SECONDS.sleep(1);
        driver.findElement(By.xpath("//*[@id=\"js-orders-modal-container\"]/div/div[2]/form/div[4]/div/div/label/input")).sendKeys("5467645380");
        TimeUnit.SECONDS.sleep(1);
        Select city  = new Select(driver.findElement(By.xpath("//*[@id=\"js-orders-modal-container\"]/div/div[2]/form/div[5]/div[1]/div/label/div/select")));
        city.selectByVisibleText("İSTANBUL");
        TimeUnit.SECONDS.sleep(1);
        Select district  = new Select(driver.findElement(By.xpath("//*[@id=\"js-orders-modal-container\"]/div/div[2]/form/div[5]/div[2]/div/label/div/select")));
        district.selectByVisibleText("ESENLER");
        TimeUnit.SECONDS.sleep(1);
        Select neighbourhood  = new Select(driver.findElement(By.xpath("//*[@id=\"js-orders-modal-container\"]/div/div[2]/form/div[6]/label/div/select")));
        neighbourhood.selectByVisibleText("ORUÇREİS MAH");
        TimeUnit.SECONDS.sleep(1);
        driver.findElement(By.xpath("//*[@id=\"js-orders-modal-container\"]/div/div[2]/form/div[7]/label/textarea")).sendKeys("592. sokak no:5 daire:5 ESENLER/İSTANBUL");
        TimeUnit.SECONDS.sleep(1);
        System.out.println("Adres bilgileri girildi.");
        driver.findElement(By.xpath("//*[@id=\"js-orders-modal-container\"]/div/div[2]/form/div[8]")).click();
        TimeUnit.SECONDS.sleep(1);
        driver.findElement(By.xpath("//*[@id=\"js-orders-modal-container\"]/div/div[2]/form/button[1]")).click();
        System.out.println("Adres bilgileri kaydedildi.");
        TimeUnit.SECONDS.sleep(2);
        driver.findElement(By.xpath("/html/body/section/section/div/div[2]/div/div[1]/div/div[2]/form/div[2]/button")).click();
        System.out.println("Kaydet ve Devam et butonuna tıklanıldı.");
        TimeUnit.SECONDS.sleep(1);
        driver.findElement(By.xpath("/html/body/section/section/div/div[3]/div[2]/div[1]/div[2]/form[1]/div[1]/div[2]/div[6]/div[1]/label/input")).sendKeys("Rabia Demir");
        TimeUnit.SECONDS.sleep(1);
        driver.findElement(By.xpath("/html/body/section/section/div/div[3]/div[2]/div[1]/div[2]/form[1]/div[1]/div[2]/div[6]/div[2]/label/input[1]")).sendKeys("4355084355084358");
        TimeUnit.SECONDS.sleep(1);
        Select month  = new Select(driver.findElement(By.xpath("/html/body/section/section/div/div[3]/div[2]/div[1]/div[2]/form[1]/div[1]/div[2]/div[6]/div[3]/div[2]/select")));
        month.selectByVisibleText("12");
        TimeUnit.SECONDS.sleep(1);
        Select year  = new Select(driver.findElement(By.xpath("/html/body/section/section/div/div[3]/div[2]/div[1]/div[2]/form[1]/div[1]/div[2]/div[6]/div[3]/div[3]/select")));
        year.selectByVisibleText("2026");
        TimeUnit.SECONDS.sleep(1);
        driver.findElement(By.xpath("/html/body/section/section/div/div[3]/div[2]/div[1]/div[2]/form[1]/div[1]/div[2]/div[6]/div[4]/label/input")).sendKeys("000");
        TimeUnit.SECONDS.sleep(2);
        System.out.println("Kart bilgileri girildi.");
        ((JavascriptExecutor) driver).executeScript("document.getElementById('agrement2').click();");
        TimeUnit.SECONDS.sleep(2);
        ((JavascriptExecutor) driver).executeScript("document.getElementsByClassName(\"order-complete\")[0].click();");
        System.out.println("Ödemeyi tamamla butonuna tıklandı.");
        System.out.println("3d ekranına gidildi.");
        System.out.println("Case başarıyla tamamlandı.");
    }
}
